# Generated by Django 2.0.4 on 2018-04-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180414_1743'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'due_date')},
        ),
    ]
