# Generated by Django 2.0.4 on 2018-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180414_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'status')},
        ),
    ]
